---

  # Finally, the ports will be opened to enable access.
- name: Open NFS ports to enable access
  become: yes
  shell: "firewall-cmd --permanent --add-service={{ item }}"
  register: result
  when: "'firewall-cmd' != item"
  with_items:
    - "{{ nfs_services }}"

  # https://www.middlewareinventory.com/blog/ansible-dict-object-has-no-attribute-stdout-or-stderr-how-to-resolve/
- name: Check output
  debug:
    msg: "Result: {{ item.item }}, {{ item.stdout }}"
  loop: "{{ result.results }}"
  loop_control:
    label: "{{ item.stdout if item == 'success' else 'skipped'}}"
  when: "'skipped' not in item"
