---

  # Here will enabled chronyd service, so we will synchronize the vms.
- name: Enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "{{ services }}"

  # Active and enable firewalld service as pretask.
- name: Enable/Start firewalld service
  become: yes
  systemd:
    state: started
    enabled: yes
    name: firewalld
