---
# https://www.middlewareinventory.com/blog/ansible-lineinfile-examples/
- name: "Disable selinux for {{ groups['cluster'] }}"
  become: yes
  become_user: root
  lineinfile:
    # Search selinux config file
    path: /etc/selinux/config
    # Search 'enforcing' ( SELINUX=enforcing )
    regexp: "SELINUX=enforcing"
    # And its disabled ( SELINUX=disabled )
    ## This is necessary to run Kubernetes in our systems
    line: "SELINUX=disabled"
    backup: yes

- name: Check SELINUX config file
  become: yes 
  register: output
  shell: cat /etc/selinux/config
  
- name: Check file
  debug:
    msg: "{{ output }}"