---

  # With this task will be create a new rule, this rule will ensure that the packets that leave 
  # our machine through an interface, change their source address for that of the exit interface.

  # Example with an explanation
  # https://myredhatcertification.wordpress.com/2015/04/26/firewalld-masquerade-forwarding-transparent-proxy/
- name: Enable transparent masquerading
  become: yes
  register: output_masq
  shell: modprobe br_netfilter && firewall-cmd --add-masquerade --permanent

- name: Reload service
  become: yes
  register: output_reload
  service:
    name: firewalld
    state: reloaded

- name: Check output
  debug:
    msg: 
      - "Enable transparent masquerade: {{ output_masq.stdout }}"
      - "Reload service result: {{ output_reload.state }}"