--- 

  # This task will allow kubernetes to correctly handle traffic with the firewall.
  # https://linuxconfig.org/how-to-turn-on-off-ip-forwarding-in-linux
- block:

  - name: Check if k8s.conf already exists
    become: yes
    register: confstat
    stat:
      path: /etc/sysctl.d/k8s.conf

  - name: Create k8s config file, if it doesnt exist already
    become: yes
    file:
      path: /etc/sysctl.d/k8s.conf
      state: touch
    when: not confstat.stat.exists

  - name: Enable firewall kube traffic
    become: yes
    register: output
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{ item.line }}"
    loop:
      - { line: net.bridge.bridge-nf-call-ip6tables = 1 }
      - { line: net.bridge.bridge-nf-call-iptables  = 1 }
      - { line: net.ipv4.ip_forward                 = 1 }

  - name: Check file content
    debug:
      msg: 
        - "Line: {{ item['invocation']['module_args'].line }}"
        - "State: {{ item['invocation']['module_args'].state }}"
    loop: "{{ output.results }}"
    loop_control:
      label: "{{ item['invocation']['module_args'].path }}"

  rescue:
    
    - name: Fail, so we will create file
      become: yes
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch
      
    - name: Enable firewall kube traffic
      become: yes
      register: output
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item.line }}"
      loop:
        - { line: net.bridge.bridge-nf-call-ip6tables = 1 }
        - { line: net.bridge.bridge-nf-call-iptables  = 1 }
        - { line: net.ipv4.ip_forward                 = 1 }

  always:

    - name: Check sysctl config
      become: yes
      register: sysctl_output
      shell: sysctl --system

    - name: Get sysctl status
      debug:
        msg: "{{ sysctl_output.stdout_lines }}"
      failed_when: ('* Applying /etc/sysctl.d/k8s.conf ...') not in (sysctl_output.stdout_lines)
