--- 

- name: Config kube repo
  become: yes
  template:
    src: templates/kuberepo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Verify /etc/yum.repos.d/kubernetes.repo
  become: yes
  register: output
  shell: cat /etc/yum.repos.d/kubernetes.repo

- name: Check Output
  debug:
    msg:  
      - "Output: {{ output.stdout.split('\n') }}"
      - "Changed: {{ output.changed }}"