---

  # Configure kubeadm that will create the basic structure of our cluster.
- name: Configure kubeadm
  become: yes
  register: output
  shell: kubeadm config images pull

- name: Check Output
  debug:
    msg:  "{{ output.stdout_lines }}"