---

  # Now, should enable workers access to master node.
  # This is controversial because we should not enable all inbound traffic since it is a security flaw, 
  # but as a practical case we omit this additional configuration.
  # https://firewalld.org/documentation/man-pages/firewalld.richlanguage.html
  ## Example 6
- name: Allow workers access
  become: yes
  register: output
  firewalld:
    rich_rule: rule family="ipv4" source address="{{ hostvars[item]['internal_ip'] }}{{ net_mask }}" accept
    permanent: yes
    state: enabled
  with_items:
    - "{{ groups['workers'] }}"

- name: Reload firewall service
  register: reload_output
  become: yes
  service:
    name: firewalld
    state: reloaded

- name: Check Output
  debug:
    msg:  
      - "Rule: {{ item['invocation']['module_args'].rich_rule }}"
      - "State: {{ item['invocation']['module_args'].state }}"
  loop: "{{ output.results }}"
  loop_control:
    label: "{{ item['item'] }}"

  # Finally, we set up our pod network where all nodes in the cluster will be in communication with each other.
- name: Init Kube and create config.yaml file {{ inventory_hostname }}
  become: yes
  shell: kubeadm init --pod-network-cidr {{ pods_net }}
  ignore_errors: true
  no_log: true