---

  # Calico will be used together with flannel to apply security policies to the network of pods.
  # https://projectcalico.docs.tigera.io/about/about-calico#:~:text=Calico%20is%20an%20open%20source,OpenStack%2C%20and%20bare%20metal%20services.
- name: Apply calico conf
  become: yes
  register: output
  shell: kubectl apply -f {{ calico_conf }}

- name: Check output
  debug: 
    msg: "{{ output.stdout_lines }}"