---

- name: Apply calico conf
  become: yes
  register: output
  shell: kubectl apply -f {{ calico_conf }}

- name: Check output
  debug: 
    msg: "{{ output.stdout_lines }}"

 # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html#examples
- name: Reboot to apply conf
  become: yes 
  run_once: true
  reboot: 
  delegate_to: "{{ item }}"
  with_items:
    - "groups['cluster']"